---
- name: Run Windows execute.cmd file
  hosts: 172.16.0.201
  tasks:
    - name: Execute .cmd file with password
      win_shell: C:\Users\inndata-dat-001\Just\ARC\execute.bat
      async: 5
      poll: 0
      register: cmd_result
 
 
    - name: Wait for the task to complete (max 5 seconds)
      async_status:
        jid: "{{ cmd_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 1
      delay: 0
      ignore_errors: true
 
 
    - name: Display task result
      debug:
        var: cmd_result
