---
- name: Uninstall Windows Exporter in Windows
  hosts: 172.16.0.122
  gather_facts: no
  tasks:
    - name: Uninstall Windows Exporter
      win_package:
        path: C:\Temp\windows_exporter\windows_exporter-0.23.1-amd64.msi
        state: absent
