---
- name: Uninstall Windows Exporter in Windows
  hosts: 172.16.0.122
  gather_facts: no
  tasks:
    - name: Uninstall Windows Exporter
      win_package:
        path: C:\Temp\windows_exporter\windows_exporter-0.23.1-amd64.msi
        state: absent

    - name: Remove Windows Exporter Installation Directory
      win_shell: Remove-Item -Path C:\Temp\windows_exporter -Recurse -Force
      when: "'C:\\Temp\\windows_exporter' is exists"

    - name: Verify Windows Exporter Installation Directory Removal
      win_stat:
        path: C:\Temp\windows_exporter
      register: win_exporter_directory
      check_mode: no
      changed_when: false

    - name: Report Windows Exporter Removal Status
      debug:
        msg: "Windows Exporter installation directory removed: {{ not win_exporter_directory.stat.exists }}"
