---
- name: Uninstall Prometheus Windows Exporter
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Stop Windows Exporter Service
      win_service:
        name: Windows-Exporter
        state: stopped
      ignore_errors: yes
    - name: Delete Windows Exporter Service
      win_shell: |
        Stop-Service "Windows-Exporter" -Force
        Remove-Service "Windows-Exporter" -Force
      ignore_errors: yes
    - name: Delete Prometheus Exporter Directory
      win_file:
        path: C:\PrometheusExporter\windows_exporter.exe
        state: absent
      ignore_errors: yes
    - name: Unregister Windows Exporter Executable
      win_command: |
        regsvr32.exe /u "C:\PrometheusExporter\windows_exporter.exe"
      ignore_errors: yes
