---
- name: Install MinIO Client on Windows
  hosts: 172.16.0.122
  gather_facts: no
  tasks:
    - name: Download MinIO Client
      win_command: |
        Invoke-WebRequest -Uri https://dl.min.io/client/mc/release/windows-amd64/mc.exe -OutFile C:\mc.exe
      args:
        executable: powershell.exe

    - name: Move MinIO Client to System32
      win_command: |
        Move-Item -Path C:\mc.exe -Destination C:\Windows\System32 -Force
      args:
        executable: powershell.exe

