---
- name: Uninstall MinIO Client from Temp Folder on Windows
  hosts: 192.168.10.9
  tasks:
    - name: Remove MinIO Client executable
      win_command: |
        Remove-Item -Path "C:\Temp\mc.exe" -Force

    - name: Remove Temp directory if empty
      win_command: |
        Remove-Item -Path "C:\Temp" -Force
