---
- name: Install MinIO Client on Windows
  hosts: 172.16.0.122
  tasks:
    - name: Create MinIO Client directory
      win_file:
        path: "C:\\Program Files\\MinIO Client"
        state: directory

    - name: Download MinIO Client
      win_get_url:
        url: https://dl.min.io/client/mc/release/windows-amd64/mc.exe
        dest: "C:\\Program Files\\MinIO Client\\mc.exe"

    - name: Add MinIO Client to PATH
      win_shell: |
        [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\Program Files\MinIO Client", [System.EnvironmentVariableTarget]::Machine)
