---
- name: Install MinIO Client on Windows
  hosts: 172.16.0.122
  tasks:
    - name: Install Chocolatey
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install MinIO Client
      win_chocolatey:
        name: minio-client
        state: present

    - name: Add MinIO Client to PATH
      win_environment:
        name: PATH
        value: "{{ ansible_env.PATH }};C:\\Program Files\\MinIO Client"
        state: present

