---
- name: Install MinIO Client on Windows
  hosts: 172.16.0.122
  gather_facts: no
  tasks:
    - name: Download MinIO Client
      win_shell: |
        Invoke-WebRequest -Uri https://dl.min.io/client/mc/release/windows-amd64/mc.exe -OutFile C:\mc.exe
      args:
        executable: powershell.exe
      become: yes

    - name: Copy MinIO Client to C:\Windows\System32
      win_copy:
        src: C:\mc.exe
        dest: C:\Windows\System32\mc.exe
      become: yes

    - name: Add C:\Windows\System32 to PATH
      win_environment:
        name: PATH
        state: present
        value: C:\Windows\System32
      become: yes

    - name: Verify MinIO Client Installation
      win_shell: mc --version
      args:
        executable: powershell.exe
      become: yes
