---
- name: Install Apache2 on CentOS 7
  hosts: all
  become: true
  tasks:
    - name: Install Apache2 package for CentOS
      yum:
        name: httpd
        state: present

    - name: Start Apache2 service
      service:
        name: httpd
        state: started
        enabled: yes
