---
- name: Install Apache HTTP Server
  hosts: all
  become: true
  tasks:
    - name: Install Apache package
      yum:
        name: httpd
        state: present

    - name: Ensure Apache service is running
      service:
        name: httpd
        state: started
        enabled: true
