---
- hosts: all
  become: yes
  tasks:
  - name: Update the system repositories
    apt:
      update_cache: yes

  - name: Install SQLite 3
    apt:
      name: sqlite3
      state: present

  - name: Check the SQLite installation
    command: sqlite3 --version
    register: sqlite_version

  - name: Assert that SQLite is installed
    assert:
      that:
        - sqlite_version.rc == 0


