---
- name: Install SQLite on Ubuntu
  hosts:
    - 172.16.0.113
    - 172.16.0.236
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
    - name: Install SQLite
      ansible.builtin.apt:
        name: sqlite3
        state: present


