---
- name: Install Windows Exporter in Windows
  hosts: 172.16.0.122
  gather_facts: no
  vars:
    windows_exporter_version: 0.23.1
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp\windows_exporter
        state: directory
    - name: Download Windows Exporter
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v{{
          windows_exporter_version }}/windows_exporter-{{
          windows_exporter_version }}-amd64.msi
        dest: C:\Temp\windows_exporter\windows_exporter-{{ windows_exporter_version
          }}-amd64.msi
    - name: Install Windows Exporter
      win_package:
        path: C:\Temp\windows_exporter\windows_exporter-{{ windows_exporter_version
          }}-amd64.msi
        state: present
    - name: Check if Windows Exporter Service Exists
      win_service:
        name: windows_exporter
      register: service_status
      ignore_errors: yes
    - name: Start Windows Exporter Service
      win_service:
        name: windows_exporter
        state: started
      when: "'Service not installed' in service_status.stderr"
    - name: Enable Windows Exporter Service at startup
      win_service:
        name: windows_exporter
        enabled: yes
      when: "'Service not installed' in service_status.stderr"
