---
- name: Install SQLite on Windows
  hosts: 172.16.0.201
  gather_facts: no
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/2023/sqlite-tools-win32-x86-3430200.zip
        dest: C:\Temp\qlite-tools-win32-x86-3430200.zip
    - name: Extract SQLite binaries
      win_unzip:
        src: C:\Temp\qlite-tools-win32-x86-3430200.zip
        dest: C:\SQLite

    - name: Add SQLite to PATH
      win_path:
        elements:
          - C:\SQLite
        state: present

    - name: Set SQLite Environment Variable
      win_environment:
        name: SQLITE_HOME
        state: present
        value: C:\SQLite

