---
- name: Install SQLite and Set Environment Variable in Windows
  hosts: 172.16.0.201
  gather_facts: yes
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory
    - name: Download SQLite Tools
      win_get_url:
        url: https://www.sqlite.org/sqlite-tools-win32-x86-3430200.zip
        dest: C:\Temp\sqlite.zip
      register: download_result
    - name: Extract SQLite Tools
      win_unzip:
        src: C:\Temp\sqlite.zip
        dest: C:\SQLite
      when: download_result.changed
    - name: Set SQLite Environment Variable
      win_environment:
        name: PATH
        value: "{{ ansible_facts['ansible_env']['PATH'] }};C:\\SQLite"
