---
- name: Install SQLite in C:\SQLite on Windows
  hosts: 172.16.0.201
  gather_facts: no
  tasks:
    - name: Create C:\SQLite Directory
      win_file:
        path: C:\SQLite
        state: directory

    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/2023/sqlite-tools-win32-x86-3430100.zip
        dest: C:\SQLite\sqlite-tools-win32-x86-3430100.zip

    - name: Extract SQLite binaries
      win_unzip:
        src: C:\SQLite\sqlite-tools-win32-x86-3430100.zip
        dest: C:\SQLite

    - name: Remove Temporary Downloaded ZIP
      win_file:
        path: C:\SQLite\sqlite-tools-win32-x86-3430100.zip
        state: absent

