---
- name: Uninstall Prometheus Windows Exporter
  hosts: 10.10.5.181
  tasks:
    - name: Stop Windows Exporter Service
      win_service:
        name: Windows-Exporter
        state: stopped
      ignore_errors: yes
    - name: Uninstall Prometheus Windows Exporter
      win_command: >
        "C:\PrometheusExporter\windows_exporter.exe"  # Replace with the
        actual path to the uninstallation utility
      ignore_errors: yes
    - name: Delete Prometheus Windows Exporter Directory
      win_file:
        path: C:P rometheusExporter\windows_exporter.exe
        state: absent
      ignore_errors: yes
    - name: Delete Prometheus Windows Exporter Service
      win_service:
        name: Windows-Exporter
        state: absent
