---
- name: Uninstall Windows Exporter and Service
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Stop Windows Exporter Service
      win_service:
        name: windows_exporter
        state: stopped
      ignore_errors: yes
    - name: Uninstall Windows Exporter Service
      win_shell: |
        sc.exe delete windows_exporter
      ignore_errors: yes
    - name: Remove Windows Exporter Files
      win_shell: |
        Remove-Item -Path 'C:\PrometheusExporter\windows_exporter' -Recurse -Force
      ignore_errors: yes
    - name: Remove Windows Exporter Service Directory
      win_shell: |
        Remove-Item -Path 'C:\PrometheusExporter\windows_exporter' -Recurse -Force
      ignore_errors: yes
    - name: Reboot the Machine
      win_reboot: null
      async: 600
      poll: 0
      register: reboot_result
      ignore_errors: yes
      when: reboot_result.rc == 0
