---
- name: Uninstall Prometheus Windows Exporter
  hosts: 172.16.0.122  # Replace with the hostname or IP of your Windows machine
  gather_facts: no
  tasks:
    - name: Stop Windows Exporter Service (if running)
      win_service:
        name: windows_exporter
        state: stopped
      ignore_errors: yes  # Ignore errors if the service is not running

    - name: Uninstall Prometheus Windows Exporter
      win_shell: |
        # Uninstall the service (if it exists)
        $serviceName = "windows_exporter"
        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
        if ($service) {
            $service | Stop-Service -Force
            $service | Remove-Service -ErrorAction SilentlyContinue
        }

        # Remove Prometheus Windows Exporter files and directory
        $exporterDirectory = "C:\temp\windows_exporter-0.23.1-amd64"  # Update with the actual directory
        Remove-Item -Path $exporterDirectory -Recurse -Force -ErrorAction SilentlyContinue

        # Remove Prometheus Windows Exporter registry entries (if any)
        Remove-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services' -Name $serviceName -ErrorAction SilentlyContinue

        # Remove Exporter-related files or artifacts as needed

      ignore_errors: yes  # Ignore errors if some resources do not exist
