---
- name: Install SQLite on Windows 10
  hosts: 10.10.5.181  # Replace with the hostname or group of Windows 10 machines
  gather_facts: no
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Download SQLite
      win_get_url:
        url: https://www.sqlite.org/new-url-for-sqlite.zip  # Update with the correct download URL
        dest: C:\Temp\sqlite.zip
      register: download_result

    - name: Unzip SQLite
      win_unzip:
        src: C:\Temp\sqlite.zip
        dest: C:\sqlite
      when: download_result.changed

    - name: Add SQLite to PATH
      win_environment:
        name: PATH
        state: present
        value: C:\sqlite
      when: download_result.changed
