---
- name: Uninstall SQLite from C:\SQLite on Windows
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Take ownership of the SQLite Directory
      win_shell: icacls 'C:\SQLite' /grant Administrators:F /T
      
    - name: Remove SQLite Directory using PowerShell
      win_shell: Remove-Item -Path 'C:\SQLite' -Recurse -Force
