---
- name: Install SQLite on Windows
  hosts: 172.16.0.201
  gather_facts: no
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/2023/sqlite-dll-win64-x64-3430200.zip
        dest: C:\Temp\sqlite-dll-win64-x64-3430200.zip

    - name: Extract SQLite binaries
      win_unzip:
        src: C:\Temp\sqlite-dll-win64-x64-3430200.zip
        dest: C:\SQLite

    - name: Add SQLite to PATH
      win_path:
        elements:
          - C:\SQLite
        state: present
