---
- name: Install SQLite on Windows
  hosts: 172.16.0.122
  gather_facts: no
  tasks:
    - name: Create Temp Directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/2023/sqlite-dll-win64-x64-3430100.zip
        dest: C:\Temp\sqlite-dll-win64-x64-3430100.zip

    - name: Extract SQLite binaries
      win_unzip:
        src: C:\Temp\sqlite-dll-win64-x64-3430100.zip
        dest: C:\SQLite

    - name: Add SQLite to PATH (PowerShell)
      win_environment:
        name: PATH
        value: "C:\\SQLite;{{ ansible_env.PATH }}"
      when: ansible_shell_type == 'powershell'

    - name: Add SQLite to PATH (Command Prompt)
      win_command: setx PATH "%PATH%;C:\SQLite" /M
      args:
        executable: cmd.exe
      when: ansible_shell_type == 'cmd'
