---
- name: Install SQLite in Windows 10
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Download SQLite precompiled binaries
      win_get_url:
        url: https://www.sqlite.org/download/sqlite-3.39.2-win64.zip
        dest: C:\Temp\sqlite-3.39.2-win64.zip
      register: download_result

    - name: Extract SQLite binaries
      unarchive:
        src: C:\Temp\sqlite-3.39.2-win64.zip
        dest: C:\SQLite

    - name: Add SQLite to PATH
      win_path:
        elements:
          - C:\SQLite

    - name: Verify SQLite is installed
      win_command: sqlite3 --version
      register: sqlite_version
      check_mode: no

    - name: Report SQLite version
      debug:
        msg: "SQLite version: {{ sqlite_version.stdout }}"


