---
- name: Install SQLite in Windows 10
  hosts: 10.10.5.181
  gather_facts: no
  tasks:
    - name: Download SQLite precompiled binaries
      win_command: >
          $webclient = New-Object System.Net.WebClient

          $webclient.DownloadFile('https://www.sqlite.org/2023/sqlite-3.39.2-win64.zip', 'C:\Temp\sqlite-3.39.2-win64.zip')
    - name: Extract SQLite binaries
      win_unzip:
        src: C:\Temp\sqlite-3.39.2-win64.zip
        dest: C:\SQLite
    - name: Add SQLite to PATH
      win_path:
        elements:
          - C:\SQLite
    - name: Verify SQLite is installed
      win_command: sqlite3 --version
      register: sqlite_version
      check_mode: no
    - name: Report SQLite version
      debug:
        msg: "SQLite version: {{ sqlite_version.stdout }}"

