---
- hosts: 192.168.210.38
  vars:
    windows_exporter_version: "0.23.1"
    windows_exporter_package_name: "windows_exporter-0.23.1-amd64.msi"
    windows_exporter_download_url: "https://github.com/prometheus-community/windows_exporter/releases/download/v0.23.1"
    windows_exporter_listen_address: "0.0.0.0"
    windows_exporter_listen_port: "9182"
    windows_exporter_metrics_path: "metrics"
    windows_exporter_log_file: "C:\Program Files\windows_exporter\exporter.log"
    windows_exporter_log_format: "logfmt"
    windows_exporter_log_level: "info"
    windows_exporter_timeout_margin: "0.5"
    windows_exporter_max_requests: "5"
    windows_exporter_collectors_enabled: "defaults"
    windows_exporter_collector: ""
    windows_exporter_tls_server_config: ""
    windows_exporter_http_server_config: ""
  tasks:
  - name: Download Windows Exporter
    win_get_url:
      url: "{{ windows_exporter_download_url }}/{{ windows_exporter_package_name }}"
      dest: "C:\Prometheus\windows_exporter.exe"

  - name: Install Windows Exporter
    win_msi:
      path: "C:\Prometheus\windows_exporter.exe"
      state: present

  - name: Configure Windows Exporter
    win_service:
      name: windows_exporter
      state: started
      enabled: yes
      config:
        metrics_path: "{{ windows_exporter_metrics_path }}"
        log_file: "{{ windows_exporter_log_file }}"
        log_format: "{{ windows_exporter_log_format }}"
        log_level: "{{ windows_exporter_log_level }}"
        timeout_margin: "{{ windows_exporter_timeout_margin }}"
        max_requests: "{{ windows_exporter_max_requests }}"
        collectors_enabled: "{{ windows_exporter_collectors_enabled }}"
        collector: "{{ windows_exporter_collector }}"
        tls_server_config: "{{ windows_exporter_tls_server_config }}"
        http_server_config: "{{ windows_exporter_http_server_config }}"

  - name: Verify Windows Exporter is running
    win_service:
      name: windows_exporter
      state: started

  - name: Check Windows Exporter is accessible
    uri:
      url: "http://localhost:{{9182 }}/{{metrics}}"
      status_code: 200

