---
- name: Install and Configure Prometheus Windows Exporter
  hosts: 10.10.5.181  # Replace with your target Windows host's IP or hostname
  gather_facts: no
  tasks:
    - name: Create Exporter Directory
      win_file:
        path: C:\PrometheusExporter
        state: directory

    - name: Download Prometheus Windows Exporter
      win_get_url:
        url: https://github.com/prometheus-community/windows_exporter/releases/download/v0.23.1/windows_exporter-0.23.1-amd64.exe
        dest: C:\PrometheusExporter\windows_exporter.exe
      register: download_result

    - name: Create Windows Exporter Service
      win_shell: |
        New-Service -Name "windows_exporter" -BinaryPathName "C:\PrometheusExporter\windows_exporter.exe --collectors.enabled=default"
      when: download_result.changed

    - name: Start Windows Exporter Service
      win_shell: Start-Service "windows_exporter"
      when: download_result.changed

    - name: Verify Windows Exporter Service is Running
      win_service:
        name: "windows_exporter"
        state: started
