---
- name: Uninstall Prometheus Windows Exporter
  hosts: 10.10.5.181  # Replace with your target Windows host's IP or hostname
  gather_facts: no
  tasks:
    - name: Stop Windows Exporter Service
      win_service:
        name: "windows_exporter"
        state: stopped
      ignore_errors: yes  # Ignore errors if the service is not running or doesn't exist

    - name: Delete Windows Exporter Service
      win_shell: |
        Stop-Service "windows_exporter" -Force
        Remove-Service "windows_exporter" -Force
      ignore_errors: yes  # Ignore errors if the service doesn't exist

    - name: Delete Prometheus Exporter Directory
      win_file:
        path: "C:\PrometheusExporter"
        state: absent
      ignore_errors: yes  # Ignore errors if the directory doesn't exist

    - name: Unregister Windows Exporter Executable
      win_command: |
        regsvr32.exe /u "C:\PrometheusExporter\windows_exporter.exe"
      ignore_errors: yes  # Ignore errors if the executable is not registered or doesn't exist
